/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

import dao.DaoAgenda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.BeansAgenda;
import model.ModeloTabela;
import util.ConexaoBD;

/**
 *
 * @author MarceloMartinsVilara
 */
public class FormAgenda extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    BeansAgenda mod = new BeansAgenda();
    BeansAgenda agen = new BeansAgenda();
    DaoAgenda daoagenda = new DaoAgenda();
     String dtHoje;
     String status = "Aberto";

    /**
     * Creates new form FormAgenda
     */
    public FormAgenda() throws ClassNotFoundException, SQLException {
        initComponents();
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        dateformat.format(d);

        
       
        dtHoje = dateformat.format(d); // data de hoje
       
        
      //  JOptionPane.showMessageDialog(null, dtHoje);
        preencherTabela("SELECT * FROM projetoclinicavilara.agendamento INNER JOIN pacientes "
                + "ON agendamento.agenda_codpac = pacientes.idPaciente INNER JOIN medicos "
                + "ON agendamento.agenda_codmedico = medicos.idMedicos "
                + "WHERE agendamento.agenda_data = '"+dtHoje+"' "
                + "AND agendamento.agenda_status = '"+status+"'");

    }

    public void preencherTabela(String Sql) throws ClassNotFoundException, SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome Paciente", "Turno", "Data", "Status", "Médico"};

        conecta.conect();
        conecta.executaSql(Sql);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("idAgenda"),
                    conecta.rs.getString("pac_nome"),
                    conecta.rs.getString("agenda_turno"),
                    conecta.rs.getString("agenda_data"),
                    conecta.rs.getString("agenda_status"),
                    conecta.rs.getString("nome_medico"),});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Não existe atendimento para hoje");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableAgendamento.setModel(modelo);
        jTableAgendamento.getColumnModel().getColumn(0).setPreferredWidth(80); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(0).setResizable(false);    // não pode ser modificado o tamanho da coluna
        jTableAgendamento.getColumnModel().getColumn(1).setPreferredWidth(228); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(1).setResizable(false);    // não pode ser modificado o tamanho da coluna
        jTableAgendamento.getColumnModel().getColumn(2).setPreferredWidth(80); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(2).setResizable(false);    // não pode ser modificado o tamanho da coluna
        jTableAgendamento.getColumnModel().getColumn(3).setPreferredWidth(120); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(3).setResizable(false);    // não pode ser modificado o tamanho da coluna

        jTableAgendamento.getColumnModel().getColumn(4).setPreferredWidth(105); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(4).setResizable(false);    // não pode ser modificado o tamanho da coluna

        jTableAgendamento.getColumnModel().getColumn(5).setPreferredWidth(129); // O zero significa qua é a primeira coluna do array
        jTableAgendamento.getColumnModel().getColumn(5).setResizable(false);    // não pode ser modificado o tamanho da coluna
        jTableAgendamento.getTableHeader().setReorderingAllowed(false);   // não pode reordenar a tabela
        jTableAgendamento.setAutoResizeMode(jTableAgendamento.AUTO_RESIZE_OFF); // tabela não pode redimensionada
        jTableAgendamento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  // só seleciona um campo por vez
        conecta.desconecta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgendamento = new javax.swing.JTable();
        jButtonAtenderAgendamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAgendamento);

        jButtonAtenderAgendamento.setText("Atender Agendamento");
        jButtonAtenderAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAtenderAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonAtenderAgendamento)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AGENDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(432, 432, 432))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(977, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgendamentoMouseClicked
      String id_agendamento = ""+jTableAgendamento.getValueAt(jTableAgendamento.getSelectedRow(), 0);
        try {
            
            conecta.conect();
            conecta.executaSql("SELECT * FROM agendamento WHERE idAgenda="+id_agendamento+"");
            conecta.rs.first();
            agen.setAgenda_status("Atendimento");
            agen.setIdAgenda(conecta.rs.getInt("idAgenda"));
       //     JOptionPane.showMessageDialog(rootPane, conecta.rs.getInt("idAgenda"));
         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            conecta.desconecta();
        } catch (SQLException ex) {
            Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableAgendamentoMouseClicked

    private void jButtonAtenderAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderAgendamentoActionPerformed
        try {
        
            daoagenda.editarAgendamentoStatus(agen);
             preencherTabela("SELECT * FROM projetoclinicavilara.agendamento INNER JOIN pacientes "
                + "ON agendamento.agenda_codpac = pacientes.idPaciente INNER JOIN medicos "
                + "ON agendamento.agenda_codmedico = medicos.idMedicos "
                + "WHERE agendamento.agenda_data = '"+dtHoje+"'"
                + "AND agendamento.agenda_status = '"+status+"'");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormAgenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtenderAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormAgenda().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormAgenda.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormAgenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtenderAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgendamento;
    // End of variables declaration//GEN-END:variables
}
